apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
        - image: danawesomedoc/gameapp:18
          name: flaskdemo
        - image: mongo:latest
          name: db
          environment:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: Tictac.player
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: db-volume
              mountPath: /data/db
          resources: {}
      volumes:
        - name: db-volume
          hostPath:
            path: /data/db
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flaskdemo
