apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: your-image-name:tag
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: app-volume
              mountPath: /app
        - name: db
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: Tictac.player
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: db-volume
              mountPath: /data/db
    volumes:
      - name: app-volume
        hostPath:
          path: /path/to/your/app
      - name: db-volume
        hostPath:
          path: /path/to/your/data
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
